sudo: required
services:
  - docker

before_install:
  - docker build -t g0717/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true g0717/react-test npm test

after_success:
  - docker build -t g0717/multi-client ./client
  - docker build -t g0717/multi-nginx ./nginx
  - docker build -t g0717/multi-server ./server
  - docker build -t g0717/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push g0717/multi-client
  - docker push g0717/multi-nginx
  - docker push g0717/multi-server
  - docker push g0717/multi-worker